# Generated by Django 3.1.7 on 2021-03-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car_Base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carparts',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
