# Generated by Django 3.1.7 on 2021-04-10 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Workers', '0003_auto_20210402_1124'),
        ('Car_Base', '0005_auto_20210408_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartsAndWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Car_Base.carparts')),
                ('works', models.ManyToManyField(to='Workers.Workers')),
            ],
        ),
    ]
